language: node_js
node_js:
 - "stable"
addons:
  code_climate:
    repo_token: f4b6ddec212ca9613de2e49e741a63efef729762a657a5463e29484e5eb54465
cache:
  directories:
    - "node_modules"
before_script:
  - npm install codeclimate-test-reporter istanbul -g
script:
  - npm test
after_script:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
